package com.macaron.corpresent.common.base;

import com.baomidou.mybatisplus.annotation.*;
import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;

/**
 * <span>
 * The primary keys of classes that inherit this entity are
 * Long type ids generated by the snowflake algorithm.
 * </span>
 *
 */
@Getter
@Setter
public class BaseAssignIDEntity implements Serializable {

    /**
     * id, incr
     */
    @TableId(type = IdType.ASSIGN_ID, value = "id")
    private Long id;

    /**
     * 创建时间
     */
    @TableField(value = "create_time", fill = FieldFill.INSERT)
    protected Long createTime;

    /**
     * 更新时间
     */
    @TableField(value = "update_time", fill = FieldFill.UPDATE)
    private Long updateTime;

    /**
     * 乐观锁
     */
    @TableField(value = "version", fill = FieldFill.INSERT)
    @Version
    private Integer version;

    /**
     * 逻辑删除
     */
    @TableField(value = "is_deleted", fill = FieldFill.INSERT)
    @TableLogic
    private Boolean isDeleted;

    /**
     * 是否禁用
     */
    @TableField(value = "is_blocked", fill = FieldFill.INSERT)
    private Boolean isBlocked;

    /**
     * 排序字段
     */
    @TableField(value = "sort", fill = FieldFill.INSERT)
    private Double sort;

}
